#!/usr/bin/env bash
#Sets custom header response

apt-get update
apt-get -y install nginx
sed -i "s/server_name _;/\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-enabled/default
service nginx start
