#!/usr/bin/env bash
# setup a load balancer
FRONTEND="frontend Local_server\n\tbind *:80\n\tmode http\n\tdefault_backend my_web_servers"
BACKEND="backend my_web_servers\n\tmode http\n\tbalance roundrobin\n\tserver 128-web-01 34.138.64.172:80 check\n\tserver 128-web-02 34.139.118.245:80 check"
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo sed -i "\$a $FRONTEND" /etc/haproxy/haproxy.cfg
sudo sed -i "\$a $BACKEND" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
