#!/usr/bin/env bash
#tell a story with info from passwd
file=/etc/passwd
while IFS=: read -r k1 k2 k3 k4 k5 k6 k7
do
        printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$k1" "$k4" "$k6" "$k7" "$k3" "$k2" "$k5"
done < $file
