#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times in 9th iterarion prints Hi
i=0
i="0"
while [ $i -lt 10 ]
do
    if [ "$i" -eq "9" ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    i=$((i + 1))
done
